### ISSUE TITLE
Windows Can't Run

### ISSUE THREAD

**Issue by SauceTV** [Kraymer/replica#3]
I'm pretty sure I'm just being stupid but how do you run this program on windows cmd
things I've tried(while navigated to my desktop where the files are located:
` 
replica -u "08-We Would Never Do.mp3" "We Would Never Do (feat. Nevve).mp3"
replica.py -u "08-We Would Never Do.mp3" "We Would Never Do (feat. Nevve).mp3"
replica.exe -u "08-We Would Never Do.mp3" "We Would Never Do (feat. Nevve).mp3"
replica "08-We Would Never Do.mp3" "We Would Never Do (feat. Nevve).mp3"
replica.py "08-We Would Never Do.mp3" "We Would Never Do (feat. Nevve).mp3"
replica.exe "08-We Would Never Do.mp3" "We Would Never Do (feat. Nevve).mp3"
`
and much more I am really lost on this and I've been looking it up for days im gonna guess its a different syntax for windows. I really have no Idea

**Comment by Kraymer** [comment]
Sorry, noticed this issue only now :(
Are you still interested to resolve this issue ?
