### ISSUE TITLE
How is order determined?

### ISSUE THREAD

**Issue by lukasb** [Kraymer/replica#8]
I just used -u on two directories. Each had files starting with 01 , 02 , .. 11 , 12 , ... etc. (that is, two digits, leading zero, space after the track number.) However, files were incorrectly swapped. How does replica decide what order to process directories in?

**Comment by Kraymer** [comment]
Ah ! replica is my oldest project, I'm not used to interact anymore with the codebase ...
Let's have a look 

By default it consider files in each folder listed alphabetically : 
~~~
❯ ./replica.py ~/Desktop/Yannick\ Noah-Live-2002 ~/Desktop/Yannick\ Noah-Live-2002-1
Cloning id3 metadata...Copy tags from /home/flap/Desktop/Yannick Noah-Live-2002/02-les_lionnes-DP.mp3 to /home/flap/Desktop/Yannick Noah-Live-2002-1/02-les_lionnes-DP.mp3
Copy tags from /home/flap/Desktop/Yannick Noah-Live-2002/07-saga_africa-DP.mp3 to /home/flap/Desktop/Yannick Noah-Live-2002-1/06-ni_divin_ni_chien-DP.mp3
Copy tags from /home/flap/Desktop/Yannick Noah-Live-2002/11-simon_papa_tara-DP.mp3 to /home/flap/Desktop/Yannick Noah-Live-2002-1/11-simon_papa_tara-DP.mp3
Copy tags from /home/flap/Desktop/Yannick Noah-Live-2002/14-la_voix_des_sages-DP.mp3 to /home/flap/Desktop/Yannick Noah-Live-2002-1/13-saga_africa-DP.mp3
Copy tags from /home/flap/Desktop/Yannick Noah-Live-2002/6-ni_divin_ni_chien-DP.mp3 to /home/flap/Desktop/Yannick Noah-Live-2002-1/14-la_voix_des_sages-DP.mp3
done
~~~
So if you miss a track in one of the folder, it creates a shift and that's not good.

The partial -p flag is a remedy to that as it pairs the tracks "smartly" using a regex.
eg see how the track numbered 6 is matched with the 06 one below

~~~
❯ ./replica.py -p ~/Desktop/Yannick\ Noah-Live-2002 ~/Desktop/Yannick\ Noah-Live-2002-1
Cloning id3 metadata...Copy tags from /home/flap/Desktop/Yannick Noah-Live-2002/02-les_lionnes-DP.mp3 to /home/flap/Desktop/Yannick Noah-Live-2002-1/02-les_lionnes-DP.mp3
Copy tags from /home/flap/Desktop/Yannick Noah-Live-2002/6-ni_divin_ni_chien-DP.mp3 to /home/flap/Desktop/Yannick Noah-Live-2002-1/06-ni_divin_ni_chien-DP.mp3
Copy tags from /home/flap/Desktop/Yannick Noah-Live-2002/11-simon_papa_tara-DP.mp3 to /home/flap/Desktop/Yannick Noah-Live-2002-1/11-simon_papa_tara-DP.mp3
Copy tags from /home/flap/Desktop/Yannick Noah-Live-2002/14-la_voix_des_sages-DP.mp3 to /home/flap/Desktop/Yannick Noah-Live-2002-1/14-la_voix_des_sages-DP.mp3
done
~~~

Conclusion: use the -p flag ? 
If you still have problems please send more details about what went wrong.
I would be willing to work again on replica to make it on par with my nowadays skills, if there is some need for people.

**Comment by lukasb** [comment]
That worked great! Thank you.

Consider making it the default?
